# Generated by Django 3.2 on 2022-11-08 10:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Motif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Receiver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='message',
            old_name='title',
            new_name='file',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='validateAS',
            new_name='valid',
        ),
        migrations.RemoveField(
            model_name='message',
            name='validateMP',
        ),
        migrations.RemoveField(
            model_name='message',
            name='validateRH',
        ),
        migrations.RemoveField(
            model_name='message',
            name='validateRT',
        ),
        migrations.AddField(
            model_name='message',
            name='ref',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='motif',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='message.motif'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='message.receiver'),
        ),
    ]
