# Generated by Django 3.2 on 2022-11-09 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_auto_20221108_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='file1',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
