# Generated by Django 3.2 on 2022-11-09 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0003_message_file1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='file1',
        ),
    ]
