# Generated by Django 3.2 on 2022-11-09 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0006_auto_20221109_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='message.receiver'),
        ),
    ]
