# Generated by Django 3.2 on 2022-11-10 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0011_auto_20221110_1100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='content',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='message',
            name='autres',
        ),
    ]
