# Generated by Django 3.2 on 2022-11-10 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0013_auto_20221110_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
