# Generated by Django 3.2 on 2022-11-10 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0014_alter_message_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='file',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
