# Generated by Django 3.2 on 2022-11-10 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0015_auto_20221110_1115'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Motif',
            new_name='TypeDemande',
        ),
        migrations.DeleteModel(
            name='Receiver',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='motif',
            new_name='typeDemande',
        ),
        migrations.RenameField(
            model_name='typedemande',
            old_name='libelle',
            new_name='type',
        ),
    ]
