# Generated by Django 3.2 on 2022-11-10 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0017_auto_20221110_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='password',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
