# Generated by Django 3.2 on 2022-11-10 20:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0018_employe_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('firstName', models.CharField(default=None, max_length=50)),
                ('password', models.CharField(max_length=100)),
                ('dateStart', models.DateTimeField(default=django.utils.timezone.now)),
                ('workplace', models.CharField(default=None, max_length=50)),
                ('job', models.CharField(default=None, max_length=50)),
                ('refAcces', models.CharField(default=None, max_length=50)),
                ('refOrdi', models.CharField(default=None, max_length=50)),
                ('refPhone', models.CharField(default=None, max_length=50)),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='message.service')),
            ],
        ),
        migrations.AlterField(
            model_name='message',
            name='employe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='message.employee'),
        ),
        migrations.DeleteModel(
            name='Employe',
        ),
    ]
