# Generated by Django 3.2 on 2022-11-11 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0019_auto_20221110_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='acces',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='ordinateur',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='telephone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
